name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Action Test Cases
        run: mvn test --file pom.xml

      - name: Clone Test Cases Repository, Change Directory, and Build/Run Tests
        run: |
          git clone https://github.com/bacao1994/tcs.git
          cd tcs
          mvn test --file pom.xml
